"use client";

import { useEffect } from "react";
import { useAppDispatch, useAppSelector } from "@/lib/store/hooks";
import { fetchMyServices } from "@/lib/features/services/services-slice";
import Link from "next/link";
import { format } from "date-fns";
import { buildCollectionKey } from "@/lib/utils/list-keys";

import { PageLogoLoader } from "@/components/ui/logo-loader";

export function ReportsView() {
    const dispatch = useAppDispatch();
    const { myServices, loading } = useAppSelector((state) => state.services);

    useEffect(() => {
        dispatch(fetchMyServices());
    }, [dispatch]);

    const reports = (myServices || []).flatMap((service: any) => {
        return (service.request_documents || [])
            .filter((doc: any) => {
                const fileName = String(doc.file_name || "").toLowerCase();
                const category = String(doc.document_category || "").toLowerCase();
                return fileName.includes("report") || category.includes("report");
            })
            .map((doc: any) => ({
                id: doc.id,
                rowKey: `report:${service.id ?? "service"}:${doc.id ?? "doc"}:${doc.file_name ?? ""}`,
                serviceName: service.service?.name,
                docName: doc.document_name || doc.document_category || "Tax Report",
                url: doc.file_url,
                date: doc.created_at || service.updated_at,
                fileName: doc.file_name
            }));
    });

    return (
        <div className="space-y-10 animate-fadeIn">
            <div>
                <h1 className="text-4xl font-black text-slate-900 tracking-tight">Tax Reports</h1>
                <p className="text-sm text-slate-500 font-bold mt-2 uppercase tracking-widest opacity-60">Audit reports and compliance summaries</p>
            </div>

            {loading ? (
                <PageLogoLoader label="Loading reports..." />
            ) : reports.length === 0 ? (
                <div className="bg-white rounded-[3rem] border-2 border-dashed border-slate-100 p-24 text-center shadow-sm">
                    <div className="h-20 w-20 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-200">
                        <i className="fas fa-file-invoice text-3xl"></i>
                    </div>
                    <h2 className="text-xl font-black text-slate-900">No reports available</h2>
                    <p className="text-sm text-slate-400 font-bold mt-2 uppercase tracking-widest mb-10">Reports generated by your accountant will appear here</p>
                    <Link href="/dashboard/services" className="h-14 px-10 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] inline-flex items-center hover:shadow-xl hover:shadow-slate-900/20 transition-all">
                        Check Progress
                    </Link>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {reports.map((r, index) => (
                        <div key={buildCollectionKey(r, index, "report", [r.rowKey, r.serviceName])} className="bg-white rounded-[2.5rem] border border-slate-100 p-8 flex items-center gap-8 hover:shadow-xl transition-all group">
                            <div className="h-20 w-20 rounded-[1.5rem] bg-slate-50 flex items-center justify-center shrink-0 group-hover:bg-blue-900 group-hover:text-white transition-all duration-500">
                                <i className="fas fa-file-alt text-2xl"></i>
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="flex justify-between items-start mb-4">
                                    <div>
                                        <p className="text-[10px] font-black text-blue-600 uppercase tracking-widest mb-1">{r.docName}</p>
                                        <h3 className="text-lg font-black text-slate-900 tracking-tight">{r.serviceName}</h3>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Date</p>
                                        <p className="text-sm font-black text-slate-900">{format(new Date(r.date), 'MMM d, yyyy')}</p>
                                    </div>
                                </div>
                                <div className="flex items-center justify-between">
                                    <div className="flex items-center gap-2">
                                        <div className="h-2 w-2 rounded-full bg-emerald-500"></div>
                                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Final Audit Report</span>
                                    </div>
                                    <a 
                                        href={r.url} 
                                        target="_blank" 
                                        rel="noopener noreferrer"
                                        className="h-10 px-6 bg-slate-100 text-slate-900 rounded-xl text-[9px] font-black uppercase tracking-widest hover:bg-slate-900 hover:text-white transition-all flex items-center gap-2"
                                    >
                                        <i className="fas fa-eye"></i>
                                        View Report
                                    </a>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
